/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GlobalDialog: typeof import('./components/GlobalDialog.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    ImageUpload: typeof import('./components/ImageUpload.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    WdActionSheet: typeof import('@wot-ui/ui/components/wd-action-sheet/wd-action-sheet.vue')['default']
    WdBadge: typeof import('@wot-ui/ui/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('@wot-ui/ui/components/wd-button/wd-button.vue')['default']
    WdConfigProvider: typeof import('@wot-ui/ui/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDatetimePicker: typeof import('@wot-ui/ui/components/wd-datetime-picker/wd-datetime-picker.vue')['default']
    WdDialog: typeof import('@wot-ui/ui/components/wd-dialog/wd-dialog.vue')['default']
    WdForm: typeof import('@wot-ui/ui/components/wd-form/wd-form.vue')['default']
    WdFormItem: typeof import('@wot-ui/ui/components/wd-form-item/wd-form-item.vue')['default']
    WdGap: typeof import('@wot-ui/ui/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('@wot-ui/ui/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('@wot-ui/ui/components/wd-input/wd-input.vue')['default']
    WdLoading: typeof import('@wot-ui/ui/components/wd-loading/wd-loading.vue')['default']
    WdNavbar: typeof import('@wot-ui/ui/components/wd-navbar/wd-navbar.vue')['default']
    WdNotify: typeof import('@wot-ui/ui/components/wd-notify/wd-notify.vue')['default']
    WdPagination: typeof import('@wot-ui/ui/components/wd-pagination/wd-pagination.vue')['default']
    WdRadio: typeof import('@wot-ui/ui/components/wd-radio/wd-radio.vue')['default']
    WdRadioGroup: typeof import('@wot-ui/ui/components/wd-radio-group/wd-radio-group.vue')['default']
    WdSearch: typeof import('@wot-ui/ui/components/wd-search/wd-search.vue')['default']
    WdSelectPicker: typeof import('@wot-ui/ui/components/wd-select-picker/wd-select-picker.vue')['default']
    WdSwitch: typeof import('@wot-ui/ui/components/wd-switch/wd-switch.vue')['default']
    WdTabbar: typeof import('@wot-ui/ui/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('@wot-ui/ui/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdTable: typeof import('@wot-ui/ui/components/wd-table/wd-table.vue')['default']
    WdTableColumn: typeof import('@wot-ui/ui/components/wd-table-column/wd-table-column.vue')['default']
    WdToast: typeof import('@wot-ui/ui/components/wd-toast/wd-toast.vue')['default']
  }
}
